#Plots
install.packages("dslabs")
library(dslabs)
data(murders)
head(murders)
install.packages("tidyverse")
library(tidyverse)
library(lubridate)
library(scales)
install.packages("tidytext")
library(tidytext)
library(broom)
install.packages("dplyr")
library(dplyr)
install.packages(data.table)
library(data.table)
install.packages("ggrepel")
library(ggrepel)
install.packages("ggthemes")
library(ggthemes)
library(ggplot2)
ds_theme_set()
# Web scrapping
install.packages("rvest")
library(rvest)
# exl read
install.packages("readxl")
library(readxl)
install.packages("RColorBrewer")
library(RColorBrewer)
install.packages("stringr")
library(stringr)
install.packages("pdftools")
library("pdftools")
install.packages("httr")
library(httr)
install.packages("textdata")
library(textdata)

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("orthogene")
install.packages("taxonomizr")
library(taxonomizr)
install.packages("rBLAST")
library(rBLAST)
library(ggplot2)
install.packages("gutenbergr")
library(gutenbergr)
ds_theme_set()
library(ggrepel)
library(ggthemes)
install.packages("Lahman")
library(Lahman)
